//LOGIN
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REFRESHTOKEN = 'REFRESHTOKEN';

//USER
export const EDIT_USER_DETAILS = 'EDIT_USER_DETAILS';
export const EDIT_USER_SETTINGS = 'EDIT_USER_SETTINGS';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';

//TYPES
export const CREATE_EXPENSE_TYPE = 'CREATE_EXPENSE_TYPE';
export const EDIT_EXPENSE_TYPE = 'EDIT_EXPENSE_TYPE';
export const REMOVE_EXPENSE_TYPE = 'REMOVE_EXPENSE_TYPE';
export const LOAD_EXPENSE_TYPES = 'LOAD_EXPENSE_TYPES';

//CATEGORIES
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';

//EXPENSES
export const CREATE_EXPENSE = 'CREATE_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const LOAD_EXPENSES = 'LOAD_EXPENSES';

//STATS
export const LOAD_CATEGORIES_BREAKDOWN = 'LOAD_CATEGORIES_BREAKDOWN';
export const LOAD_EXPENSES_BREAKDOWN = 'LOAD_EXPENSES_BREAKDOWN';
export const EDIT_STATISTICS = 'EDIT_STATISTICS';
export const CREATE_NEWCATEGORY_STATISTICS = 'CREATE_NEWCATEGORY_STATISTICS';
export const EDIT_CATEGORY_STATISTICS = 'EDIT_CATEGORY_STATISTICS';
export const DELETE_CATEGORY_STATISTICS = 'DELETE_CATEGORY_STATISTICS';

//ALERT
export const ADD_ALERT = 'ADD_ALERT';

//LOADING
export const TOGGLE_LOADING = 'TOGGLE_LOADING';