//LOGIN
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

//TYPES
export const ADD_EXPENSE_TYPE = 'ADD_EXPENSE_TYPE';
export const EDIT_EXPENSE_TYPE = 'EDIT_EXPENSE_TYPE';
export const REMOVE_EXPENSE_TYPE = 'REMOVE_EXPENSE_TYPE';
export const GET_EXPENSE_TYPES = 'GET_EXPENSE_TYPES';


//CATEGORIES
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';

//ALERT
export const SET_ALERT = 'SET_ALERT';

//LOADING
export const SET_LOADING = 'SET_LOADING';