//LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

//TYPES
export const CREATE_EXPENSE_TYPE = 'CREATE_EXPENSE_TYPE';
export const UPDATE_EXPENSE_TYPE = 'UPDATE_EXPENSE_TYPE';
export const DELETE_EXPENSE_TYPE = 'DELETE_EXPENSE_TYPE';
export const SET_EXPENSE_TYPE = 'SET_EXPENSE_TYPE';


//CATEGORIES
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SET_CATEGORIES = 'SET_CATEGORIES';

//EXPENSES
export const CREATE_EXPENSE = 'CREATE_EXPENSE';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const SET_EXPENSES = 'SET_EXPENSES';

//ALERT
export const ADD_ALERT = 'ADD_ALERT';

//LOADING
export const UPDATE_LOADING = 'UPDATE_LOADING';