//LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

//USER
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';

//CURRENCIES
export const SET_CURRENCIES = 'SET_CURRENCIES';

//TYPES
export const ADD_EXPENSE_TYPE = 'ADD_EXPENSE_TYPE';
export const UPDATE_EXPENSE_TYPE = 'UPDATE_EXPENSE_TYPE';
export const DELETE_EXPENSE_TYPE = 'DELETE_EXPENSE_TYPE';
export const SET_EXPENSE_TYPE = 'SET_EXPENSE_TYPE';
export const DELETE_EXPENSESOFTYPE = 'DELETE_EXPENSESOFTYPE'; 

//CATEGORIES
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const DELETE_EXPENSESOFCATEGORY = 'DELETE_EXPENSESOFCATEGORY';

//EXPENSES
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const SET_EXPENSES = 'SET_EXPENSES';

//STATS
export const SET_CATEGORIES_BREAKDOWN = 'SET_CATEGORIES_BREAKDOWN';
export const SET_EXPENSES_BREAKDOWN = 'SET_EXPENSES_BREAKDOWN';
export const UPDATE_STATISTICS = 'UPDATE_STATISTICS';
export const ADD_NEWCATEGORY_STATISTICS = 'ADD_NEWCATEGORY_STATISTICS';
export const UPDATE_CATEGORY_STATISTICS = 'UPDATE_CATEGORY_STATISTICS';
export const REMOVE_CATEGORY_STATISTICS = 'REMOVE_CATEGORY_STATISTICS';

//ALERT
export const CREATE_ALERT = 'CREATE_ALERT';

//LOADING
export const UPDATE_LOADING = 'UPDATE_LOADING';